options:
  install_sources:
    description: >
        List of extra apt sources, per charm-helpers standard
        format (a yaml list of strings encoded as a string). Each source
        may be either a line that can be added directly to
        sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
        Personal Package Archives, or a distribution component to enable.
    type: string
    default: |
      - "http://dl.openfoam.org/ubuntu"
  install_keys:
    description: >
        List of signing keys for install_sources package sources, per
        charmhelpers standard format (a yaml list of strings encoded as
        a string). The keys should be the full ASCII armoured GPG public
        keys. While GPG key ids are also supported and looked up on a
        keyserver, operators should be aware that this mechanism is
        insecure. null can be used if a standard package signing key is
        used that will already be installed on the machine, and for PPA
        sources where the package signing key is securely retrieved from
        Launchpad.
    type: string
    default: |
      - |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1
        
        mQENBFeGXxcBCACpBHAlBk67MVnHtLux0eI/gJuo5eTSLzQd4TYXgLbOXs8aCEH1
        7JKAS24m2KwtcqBwTfW+wb54b0HHzJn81Zpmd7JXt/6oX4wZHTXMED9/P893UHOI
        sC5e1O9BzDQ4J1Ot4SMMRElNZyxdcbqGTvp+t67xrBqG1ZoXO4WYfUemNT+I4xrs
        xzguKVvL+yWB8hHZ6JpzScC3xQM9JSL7Gzmv6NvXkr+fDw6Ct/aUdB3PjbSlINKC
        4sTfQRvokE6nf7SVMqiPTDup+E1DLLfzvUJSxoCGc34wbiuA5ThqE11Y4DiLZaLe
        r3V03nbEJY2T1cGExS7njMs3uFiICovfWdmXABEBAAG0KE9wZW5GT0FNIEZvdW5k
        YXRpb24gPGFkbWluQG9wZW5mb2FtLm9yZz6JATcEEwEKACEFAleGXxcCGwMFCwkI
        BwMFFQoJCAsFFgMCAQACHgECF4AACgkQbA2scosp2BdYdAf+K1+RfWZZSZBwqpPR
        MNvV8RkpQ5k7m68NdFRha6cmxCnFJwyw7EJrI0ZXrnz+VstmTvTt05a2ml3MvMdK
        WBZs0/dA3LuqYLjGCPCDB5iu5w/sVCXyawZejoe/X3/ODRDgUiJ1LCKQbhwHqNda
        yIH7gBYdmy3bzjncm5lYn/Jxw42qAOog/Lnwrru5EIeTyNWrk495KEjTasb9L31I
        61G5oEkZsoDk6kPIf93lHBzey60wyc3dU6jQAbnjCB1PvcQP12uv8MK0bO6E5TKS
        BYj/W3wayzaU/FD7NIbCbsHqc1rDNDutp3Y6B5z3tP3bSJ70FfoWfGWuuPG6uEJy
        W5EHUbkBDQRXhl8XAQgAxQnYD9yvl19ULD3el+vhwUb+xIj2gkpyCfP3g6as68OR
        6QsHfYyFrLxBCroGb/fx4AT240ikErplgYThr+fwVl8CXyWtdrgrUwU8DopTTiTN
        xYxbxklljp8ZO8rJNPpIWJBTIUSZv+2sd+LrkcEocZ0tWsUoshlc3iBYtmiO+HbW
        9yAxKHOkA3eooSZHERs8BIQ+ZLhv3x5FB73jbMYOIB0dqU2GrbDvFBnKx9AWheCd
        JsOAlAlGnNcyI4ZDdJ33DozCUgalxmTMGrfPyCvz9zqKm1gQsscmrNFij/F9TeNY
        +oEjRoXwwnyM5YiexMcxhLp2NPjagFU0lNS8gCFy2QARAQABiQEfBBgBCgAJBQJX
        hl8XAhsMAAoJEGwNrHKLKdgXShUH/1rUNk9MvoZ9HBdvm7/z70J64cnNPjIwPuhO
        5FMihCMmnsESjCgzrP6rVDOma4psf7fwEe8m1cltl8gVQ1cZIo2LO/0XnbBeo9b9
        hA+RqtKz9IZYqNzbvGxEbkhMf6O/TDSFmJpAueh8D3/Dgcrvya0bflkwoGl7RDKu
        Iq68v4Ri1s4LAq8RCIsB85NKds2vLIAuMrhbhtwYEVgalPotMMHX/MMrKL5T95Ac
        /GuySu+Yk7kmfrFq0SIzP1BFGv+l84ke18zMu0ssGHVGY0eaEEpO2aude+HhMJqD
        +PmSM0ZDHsJu4It2PIIGtgGWfai9ddXOI2+z8W6ugsKr/tq7Sik=
        =DlyX
        -----END PGP PUBLIC KEY BLOCK-----
